arms:
  aira_zero:
    config:
      home_position:
        base: -0.01697566186007471
        gripper: 0.5186160067139713
        link1: -0.994697489890898
        link2: -1.1324101625085827
        link3: -0.9512092774853134
        link4: 0.05092698558022413
        link5: 0.029564354924849212
    enabled: true
    motor_type: damiao
    name: Aira Zero Follower
    port: can0
    role: follower
    structural_design: damiao_7dof
  aira_zero_leader:
    enabled: true
    motor_type: dynamixel_xl330
    name: Aira Zero Leader
    port: /dev/ttyACM0
    role: leader
    structural_design: umbra_7dof
  umbra_follower:
    enabled: true
    motor_type: sts3215
    name: 'Umbra Follower '
    port: /dev/ttyUSB0
    role: follower
    structural_design: umbra_7dof
  umbra_leader:
    enabled: true
    motor_type: dynamixel_xl330
    name: Umbra Leader
    port: /dev/ttyACM1
    role: leader
    structural_design: umbra_7dof
pairings:
- follower: aira_zero
  leader: aira_zero_leader
  name: Aira Zero Leader -> Aira Zero Follower
- follower: umbra_follower
  leader: umbra_leader
  name: 'Umbra Leader -> Umbra Follower '
robot:
  cameras:
    camera_1:
      fps: 30
      height: 480
      serial_number_or_name: '336222072963'
      type: intelrealsense
      use_depth: false
      video_device_id: '336222072963'
      width: 640
    camera_2:
      fps: 30
      height: 480
      serial_number_or_name: '218622275492'
      type: intelrealsense
      use_depth: false
      video_device_id: '218622275492'
      width: 640
teleop:
  gripper_force_feedback: true
  joint_force_feedback: false
tool_pairings:
- action: toggle
  config: {}
  name: Screwdriver Trigger -> Main Screwdriver
  tool_id: screwdriver_1
  trigger_id: button1
tools:
  screwdriver_1:
    config:
      direction: -1
      speed: 2000
    enabled: true
    motor_id: 8
    motor_type: sts3215
    name: Main Screwdriver
    port: /dev/ttyUSB1
    tool_type: screwdriver
training:
  batch_size: 8
  offline_steps: 10000
  policy: diffusion
  steps: 5000
triggers:
  button1:
    active_low: true
    enabled: true
    name: Screwdriver Trigger
    pin: 0
    port: /dev/ttyACM2
    trigger_type: gpio_switch
