robot:
  cameras:
  - fps: 30
    height: 480
    id: camera_1
    video_device_id: '218622275492'
    width: 848
  - fps: 30
    height: 480
    id: camera_2
    video_device_id: /dev/video6
    width: 640
  - fps: 30
    height: 480
    id: camera_3
    video_device_id: /dev/video10
    width: 640
  id: umbra_bi_2
  left_arm_port: /dev/ttyUSB3
  right_arm_port: /dev/ttyUSB1
  type: bi_umbra_follower
teleop:
  id: leader_bi_3
  left_arm_port: /dev/ttyUSB0
  right_arm_port: /dev/ttyUSB2
  type: bi_umbra_leader
training:
  batch_size: 8
  offline_steps: 10000
  policy: diffusion
  steps: 5000
