robot:
  cameras:
  - fps: 30
    height: 720
    id: camera_1
    video_device_id: /dev/video2
    width: 1280
  - fps: 30
    height: 720
    id: camera_2
    video_device_id: /dev/video4
    width: 1280
  - fps: 30
    height: 720
    id: camera_3
    width: 1280
  id: umbra_bi_2
  left_arm_port: /dev/ttyUSB3
  right_arm_port: /dev/ttyUSB1
  type: bi_umbra_follower
teleop:
  id: leader_bi_3
  left_arm_port: /dev/ttyUSB0
  right_arm_port: /dev/ttyUSB2
  type: bi_umbra_leader
training:
  batch_size: 8
  offline_steps: 10000
  policy: diffusion
  steps: 5000
